import React, {useEffect,useMemo,useRef,useState} from 'react';
import { createRoot } from 'react-dom/client';
import ForceGraph3D from 'react-force-graph-3d';
import {Search, Download, Upload, Settings2, Presentation, Route, Plus, Undo2, Redo2, X, Network, ChevronRight, Focus, Trash2, Save, RotateCcw, BarChart3} from 'lucide-react';
import './style.css';

const domains={Payments:'#8b5cf6',Risk:'#fb7185','Core Banking':'#38bdf8',Data:'#2dd4bf',Operations:'#fbbf24',Customer:'#a3e635'};
const types={kafka:'#f59e0b',rest:'#38bdf8',db:'#a78bfa',event:'#2dd4bf',grpc:'#fb7185',other:'#94a3b8'};
const defaultGraph={nodes:[],links:[]};
const asId=x=>typeof x==='object'?x.id:x;
const neighbors=(g,id,direction='both')=>g.links.filter(l=> direction==='out'?asId(l.source)===id:direction==='in'?asId(l.target)===id:asId(l.source)===id||asId(l.target)===id).map(l=>asId(l.source)===id?asId(l.target):asId(l.source));
function shortestPaths(g,start,end,max=4,depth=7){const out=[]; const q=[[start]]; while(q.length&&out.length<max){const p=q.shift(), last=p.at(-1); if(last===end){out.push(p);continue} if(p.length>depth)continue; for(const n of neighbors(g,last)) if(!p.includes(n))q.push([...p,n])} return out}
function App(){
 const graphRef=useRef(); const fileRef=useRef(); const [base,setBase]=useState(defaultGraph),[graph,setGraph]=useState(defaultGraph),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[domainsFilter,setDomainsFilter]=useState([]),[nodeFilter,setNodeFilter]=useState([]),[linkFilter,setLinkFilter]=useState([]),[mode,setMode]=useState('View'),[drawer,setDrawer]=useState('paths'),[a,setA]=useState(''),[b,setB]=useState(''),[paths,setPaths]=useState([]),[focusPath,setFocusPath]=useState(null),[impact,setImpact]=useState(null),[depth,setDepth]=useState(2),[history,setHistory]=useState([]),[redo,setRedo]=useState([]),[form,setForm]=useState(null),[presentation,setPresentation]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>{fetch('./data/graph.json').then(r=>r.json()).then(g=>{setGraph(g);setBase(g)})},[]);
 const selectedId=selected?.kind==='node'?selected.data.id:null;
 const visible=useMemo(()=>{let ns=graph.nodes.filter(n=>(!domainsFilter.length||domainsFilter.includes(n.domain))&&(!nodeFilter.length||nodeFilter.includes(n.type))); if(focusPath!==null)ns=ns.filter(n=>paths[focusPath]?.includes(n.id)); const ids=new Set(ns.map(n=>n.id)); let ls=graph.links.filter(l=>ids.has(asId(l.source))&&ids.has(asId(l.target))&&(!linkFilter.length||linkFilter.includes(l.type))); return {nodes:ns,links:ls}},[graph,domainsFilter,nodeFilter,linkFilter,focusPath,paths]);
 const highlighted=useMemo(()=>{const s=new Set(); if(selectedId){s.add(selectedId); const walk=(id,d)=>{if(!d)return; neighbors(graph,id).forEach(n=>{s.add(n);walk(n,d-1)})};walk(selectedId,depth)} if(impact) impact.ids.forEach(x=>s.add(x)); return s},[graph,selectedId,depth,impact]);
 const update=(next,action)=>{setHistory(h=>[...h,graph]);setRedo([]);setGraph(next);if(action)setToast(action)};
 const download=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(graph,null,2)],{type:'application/json'}));const e=document.createElement('a');e.href=u;e.download='graph.json';e.click();URL.revokeObjectURL(u)};
 const doImpact=(dir)=>{if(!selectedId)return; const seen=new Set([selectedId]), queue=[[selectedId,0]]; while(queue.length){const [id,d]=queue.shift();if(depth!=='all'&&d>=depth)continue; graph.links.forEach(l=>{const s=asId(l.source),t=asId(l.target);const next=dir==='upstream'&&t===id?s:dir==='downstream'&&s===id?t:null;if(next&&!seen.has(next)){seen.add(next);queue.push([next,d+1])}})}setImpact({dir,ids:seen})};
 const commitForm=()=>{try{let p={...form.data,tech:(form.data.tech||'').split(',').map(x=>x.trim()).filter(Boolean),links:(form.data.links||'').split(',').filter(Boolean),meta:typeof form.data.meta==='string'?JSON.parse(form.data.meta||'{}'):form.data.meta};if(form.kind==='node'){if(!p.name)throw Error('Введите название');p.id=p.id||`node-${Date.now()}`;const exists=graph.nodes.some(n=>n.id===p.id&&n.id!==form.original?.id);if(exists)throw Error('ID уже используется');const nodes=form.original?graph.nodes.map(n=>n.id===form.original.id?p:n):[...graph.nodes,p];update({...graph,nodes},form.original?'Нода обновлена':'Нода добавлена')}else{p.id=p.id||`link-${Date.now()}`;if(!p.source||!p.target)throw Error('Выберите обе системы');const links=form.original?graph.links.map(l=>l.id===form.original.id?p:l):[...graph.links,p];update({...graph,links},form.original?'Связь обновлена':'Связь добавлена')}setForm(null)}catch(e){setToast(e.message)}};
 const selectNode=n=>{setSelected({kind:'node',data:n});setImpact(null);setFocusPath(null)};
 const selectLink=l=>setSelected({kind:'link',data:l});
 const remove=()=>{if(!selected)return;if(!confirm('Удалить выбранный объект?'))return; if(selected.kind==='node'){update({...graph,nodes:graph.nodes.filter(n=>n.id!==selected.data.id),links:graph.links.filter(l=>asId(l.source)!==selected.data.id&&asId(l.target)!==selected.data.id)},'Нода удалена')}else update({...graph,links:graph.links.filter(l=>l.id!==selected.data.id)},'Связь удалена');setSelected(null)};
 const toggle=(set,val,x)=>set(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);
 const stats=useMemo(()=>({critical:[...graph.nodes].sort((a,b)=>b.criticality-a.criticality).slice(0,5),domains:Object.entries(graph.nodes.reduce((a,n)=>(a[n.domain]=(a[n.domain]||0)+1,a),{}))}),[graph]);
 return <div className={presentation?'app presentation':'app'}><header><div className="brand"><Network size={22}/><span>ATLAS</span><b>integration intelligence</b></div><div className="headerActions"><button className={mode==='Edit'?'active':''} onClick={()=>setMode(mode==='View'?'Edit':'View')}>{mode==='View'?'View mode':'Edit mode'}</button><button onClick={()=>setPresentation(!presentation)}><Presentation size={16}/> Presentation</button><button onClick={()=>setDrawer('stats')}><BarChart3 size={16}/> Stats</button><button onClick={download}><Download size={16}/> JSON</button><button onClick={()=>fileRef.current.click()}><Upload size={16}/> Import</button><input ref={fileRef} type="file" hidden accept=".json" onChange={e=>{const r=new FileReader();r.onload=()=>{try{const g=JSON.parse(r.result);if(!g.nodes||!g.links)throw Error();update(g,'Граф импортирован')}catch{setToast('Неверный формат JSON')}};r.readAsText(e.target.files[0])}}/></div></header>
 <section className="controls"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search systems, teams, data stores…"/></label><Filter title="Domain" items={Object.keys(domains)} values={domainsFilter} toggle={x=>toggle(setDomainsFilter,domainsFilter,x)}/><Filter title="Node type" items={['system','service','datastore','team']} values={nodeFilter} toggle={x=>toggle(setNodeFilter,nodeFilter,x)}/><Filter title="Link type" items={Object.keys(types).slice(0,5)} values={linkFilter} toggle={x=>toggle(setLinkFilter,linkFilter,x)}/><div className="pathbar"><Route size={17}/><select value={a} onChange={e=>setA(e.target.value)}><option value="">Node A</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select><ChevronRight size={15}/><select value={b} onChange={e=>setB(e.target.value)}><option value="">Node B</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select><button className="primary" onClick={()=>{if(a&&b){setPaths(shortestPaths(graph,a,b));setDrawer('paths');setFocusPath(null)}else setToast('Выберите два узла')}}>Find paths</button></div></section>
 <main><div className="graph"><ForceGraph3D ref={graphRef} graphData={visible} backgroundColor="#070b16" nodeLabel={n=>`<b>${n.name}</b><br/>${n.domain} · ${n.owner}<br/>Criticality ${n.criticality}/5<br/>${n.description}`} linkLabel={l=>`${asId(l.source)} → ${asId(l.target)} · ${l.protocol}`} nodeColor={n=>highlighted.size&&!highlighted.has(n.id)?'#1e293b':query&&!n.name.toLowerCase().includes(query.toLowerCase())?'#263246':domains[n.domain]} nodeVal={n=>2+n.criticality*1.35} nodeOpacity={.94} nodeLabelColor="#fff" linkColor={l=>paths.some(p=>p.some((id,i)=>i&&((p[i-1]===asId(l.source)&&id===asId(l.target))||(p[i-1]===asId(l.target)&&id===asId(l.source)))))?'#f8fafc':types[l.type]} linkWidth={l=>highlighted.has(asId(l.source))&&highlighted.has(asId(l.target))?2.5:0.7} linkDirectionalArrowLength={3} linkDirectionalArrowRelPos={.92} onNodeClick={selectNode} onLinkClick={selectLink} d3VelocityDecay={.25}/><div className="legend">{Object.entries(domains).map(([n,c])=><span key={n}><i style={{background:c}}/>{n}</span>)}</div>{mode==='Edit'&&<div className="editTools"><button className="primary" onClick={()=>setForm({kind:'node',data:{type:'service',domain:'Payments',criticality:3,tech:'',links:'',meta:'{}',owner:'',description:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}><Plus size={16}/> Add node</button><button onClick={()=>setForm({kind:'link',data:{type:'rest',direction:'source->target',protocol:'',sla:'',description:'',meta:'{}',metrics:{},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}})}><Plus size={16}/> Add link</button><button onClick={()=>{if(history.length){setRedo(r=>[graph,...r]);setGraph(history.at(-1));setHistory(h=>h.slice(0,-1))}}}><Undo2 size={16}/></button><button onClick={()=>{if(redo.length){setHistory(h=>[...h,graph]);setGraph(redo[0]);setRedo(r=>r.slice(1))}}><Redo2 size={16}/></button><button onClick={()=>{setGraph(base);setHistory([]);setToast('Восстановлен mock-граф')}}><RotateCcw size={16}/></button></div>}</div><aside><Detail selected={selected} graph={graph} mode={mode} selectNode={selectNode} onImpact={doImpact} setDepth={setDepth} depth={depth} onForm={setForm} remove={remove}/><div className="tabs"><button className={drawer==='paths'?'on':''} onClick={()=>setDrawer('paths')}>Paths</button><button className={drawer==='stats'?'on':''} onClick={()=>setDrawer('stats')}>Statistics</button></div>{drawer==='paths'?<Paths paths={paths} graph={graph} setFocusPath={setFocusPath}/>:<Stats stats={stats} graph={graph}/>}</aside></main>{form&&<Editor form={form} setForm={setForm} graph={graph} commit={commitForm}/>} {toast&&<div className="toast" onAnimationEnd={()=>setToast('')}>{toast}</div>}</div>}
function Filter({title,items,values,toggle}){return <details className="filter"><summary>{title}{values.length?` · ${values.length}`:''}</summary><div>{items.map(x=><label key={x}><input type="checkbox" checked={values.includes(x)} onChange={()=>toggle(x)}/>{x}</label>)}</div></details>}
function Detail({selected,graph,mode,selectNode,onImpact,setDepth,depth,onForm,remove}){if(!selected)return <div className="detail empty"><div className="orb"/><h2>Explore your landscape</h2><p>Click a system or integration to inspect dependencies, ownership and operational context.</p></div>;const {kind,data}=selected;const node=kind==='node';const entries=node?[['Type',data.type],['Domain',data.domain],['Owner',data.owner],['Criticality',`${data.criticality} / 5`]]:[['From',asId(data.source)],['To',asId(data.target)],['Type',data.type],['Protocol',data.protocol],['Direction',data.direction],['SLA',typeof data.sla==='string'?data.sla:JSON.stringify(data.sla)]];return <div className="detail"><div className="eyebrow">{node?'SYSTEM DETAILS':'INTEGRATION DETAILS'}</div><h2>{node?data.name:`${asId(data.source)} → ${asId(data.target)}`}</h2><p>{data.description}</p><div className="facts">{entries.map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div>{node&&<><div className="chips">{data.tech?.map(t=><span key={t}>{t}</span>)}</div><div className="impact"><label>Impact depth <select value={depth} onChange={e=>setDepth(e.target.value==='all'?'all':+e.target.value)}><option value="1">1 hop</option><option value="2">2 hops</option><option value="3">3 hops</option><option value="all">All</option></select></label><button onClick={()=>onImpact('upstream')}>Show upstream</button><button onClick={()=>onImpact('downstream')}>Show downstream</button></div><h3>Connected integrations</h3><div className="connections">{graph.links.filter(l=>asId(l.source)===data.id||asId(l.target)===data.id).slice(0,8).map(l=>{const other=asId(l.source)===data.id?asId(l.target):asId(l.source);return <button key={l.id} onClick={()=>selectNode(graph.nodes.find(n=>n.id===other))}>{other}<small>{l.type} · {l.protocol}</small></button>})}</div></>}{!node&&<pre>{JSON.stringify(data.metrics,null,2)}</pre>}{mode==='Edit'&&<div className="editActions"><button onClick={()=>onForm({kind:node?'node':'link',original:data,data:{...data,tech:node?(data.tech||[]).join(', '):undefined,links:node?(data.links||[]).join(', '):undefined,meta:JSON.stringify(data.meta||{})}})}>Edit</button><button className="danger" onClick={remove}><Trash2 size={14}/> Delete</button></div>}</div>}
function Paths({paths,graph,setFocusPath}){return <section className="panel"><h3>Route explorer</h3>{!paths.length?<p className="muted">Choose two nodes to discover alternative dependency routes.</p>:paths.map((p,i)=><article className="path" key={i}><div><b>Path {i+1}</b><span>{p.length-1} hops</span></div><ol>{p.map(id=><li key={id}>{graph.nodes.find(n=>n.id===id)?.name||id}</li>)}</ol><button onClick={()=>setFocusPath(i)}><Focus size={14}/> Focus route</button><button onClick={()=>navigator.clipboard?.writeText(JSON.stringify(p))}>Copy JSON</button></article>)}</section>}
function Stats({stats,graph}){return <section className="panel"><h3>Graph statistics</h3><div className="statnums"><b>{graph.nodes.length}<small>nodes</small></b><b>{graph.links.length}<small>links</small></b></div><h4>Domains</h4>{stats.domains.map(([n,c])=><div className="bar" key={n}><span>{n}</span><i style={{width:`${c/graph.nodes.length*100}%`}}/><b>{c}</b></div>)}<h4>Most critical</h4>{stats.critical.map(n=><div className="rank" key={n.id}><span>{n.name}</span><b>{n.criticality}/5</b></div>)}</section>}
function Editor({form,setForm,graph,commit}){const d=form.data, isNode=form.kind==='node';const set=(k,v)=>setForm({...form,data:{...d,[k]:v}});return <div className="modalback"><form className="modal" onSubmit={e=>{e.preventDefault();commit()}}><button type="button" className="close" onClick={()=>setForm(null)}><X/></button><div className="eyebrow">EDIT MODE</div><h2>{form.original?'Edit':'Create'} {isNode?'node':'integration'}</h2><div className="formgrid">{(isNode?['id','name','owner','description','tech','links']:['id','protocol','sla','description']).map(k=><label key={k}>{k}<input value={d[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}{isNode?<><label>type<select value={d.type} onChange={e=>set('type',e.target.value)}>{['system','service','datastore','team'].map(x=><option>{x}</option>)}</select></label><label>domain<select value={d.domain} onChange={e=>set('domain',e.target.value)}>{Object.keys(domains).map(x=><option>{x}</option>)}</select></label><label>criticality<input type="number" min="1" max="5" value={d.criticality} onChange={e=>set('criticality',+e.target.value)}/></label></>:<><label>source<select value={d.source||''} onChange={e=>set('source',e.target.value)}><option value="">Select</option>{graph.nodes.map(n=><option value={n.id}>{n.name}</option>)}</select></label><label>target<select value={d.target||''} onChange={e=>set('target',e.target.value)}><option value="">Select</option>{graph.nodes.map(n=><option value={n.id}>{n.name}</option>)}</select></label><label>type<select value={d.type} onChange={e=>set('type',e.target.value)}>{Object.keys(types).map(x=><option>{x}</option>)}</select></label><label>direction<select value={d.direction} onChange={e=>set('direction',e.target.value)}>{['source->target','target->source','bidirectional'].map(x=><option>{x}</option>)}</select></label></>}<label className="wide">meta (JSON)<textarea value={d.meta||'{}'} onChange={e=>set('meta',e.target.value)}/></label></div><button className="primary save"><Save size={16}/> Save changes</button></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
